version: "3.9"

services:
  teams-export:
    image: demisto/powershell:7.5.0.3759715
    container_name: teams-export
    working_dir: /code
    stdin_open: true
    tty: true
    volumes:
      - .:/code
    environment:
      # from 学生連絡 https://teams.microsoft.com/l/team/19%3Acbff82e7a06347fbbbca1e2551b2d1d5%40thread.tacv2/conversations?groupId=1e1d6188-3a9c-4659-b332-618c6c683daa&tenantId=ceb2991d-5710-405b-9a3b-3dab6a109547
      - TEAMS_GROUP_ID=1e1d6188-3a9c-4659-b332-618c6c683daa
    command:
      - pwsh
      - -Command
      - |
        Install-Module MicrosoftTeams -Force -AllowClobber -Confirm:$$false;
        Connect-MicrosoftTeams -UseDeviceAuthentication;
        Get-TeamUser -GroupId $$env:TEAMS_GROUP_ID |
        Export-Csv -Encoding UTF8 -NoTypeInformation -Path /code/users.csv