version: "3.9"

services:
  teams-export:
    image: demisto/powershell:7.5.0.3759715
    container_name: teams-export
    working_dir: /scripts
    volumes:
      - ./output:/scripts
    command:
      - pwsh
      - -Command
      - |
        Install-Module MicrosoftTeams -Force -AllowClobber -Confirm:$false;
        $grupeID = "a928e083-b1c3-4b41-addd-22a2e300138e";
        Connect-MicrosoftTeams -UseDeviceAuthentication;
        Get-TeamUser -GroupId $grupeID |
        Export-Csv -Encoding UTF8 -NoTypeInformation -Path ./output
