services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: resohub-frontend
    ports:
      - 8000:3000
    volumes:
      - ./frontend/:/app
      - /app/node_modules
      - ./README.md:/app/readme/README.md
      - ./frontend/README.md:/app/readme/frontend-README.md
      - ./backend/README.md:/app/readme/backend-README.md
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    env_file:
      - .env
    stdin_open: true
    tty: true
    networks:
      - app-network
    restart: unless-stopped
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: resohub-backend
    ports:
      - 8001:8000
    volumes:
      - ./backend/:/app
    env_file:
      - .env
    stdin_open: true
    tty: true
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge