services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: resohub-frontend
    ports:
      - 8000:3000
    volumes:
      - ./frontend/:/app
      - /app/node_modules
      - ./README.md:/app/readme/README.md
      - ./frontend/README.md:/app/readme/frontend-README.md
      - ./backend/README.md:/app/readme/backend-README.md
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    env_file:
      - .env
    stdin_open: true
    tty: true
    networks:
      - app-network
    restart: unless-stopped
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: resohub-backend
    ports:
      - 8001:8000
    volumes:
      - ./backend/:/app
    env_file:
      - .env
    stdin_open: true
    tty: true
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:9.4.0
    container_name: resohub-db
    environment:                  
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django-db
      MYSQL_USER: django
      MYSQL_PASSWORD: django
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "django", "-pdjango"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - app-network
  minio:
    image: minio/minio:latest
    ports:
      - 9001:9001
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - app-network
  minio-client:
    image: minio/mc:latest
    entrypoint: >
      /bin/sh -c "  
      /usr/bin/mc config host rm expo;  
      /usr/bin/mc config host add --quiet --api s3v4 local http://minio:9000 minio minio123;  
      /usr/bin/mc rb --force local/<your-bucket-name>/;  
      /usr/bin/mc mb --quiet local/<your-bucket-name>/;  
      /usr/bin/mc policy set public local/<your-bucket-name>;  
      "
    depends_on:
      - minio
    networks:
      - app-network

volumes:
  minio-data:

networks:
  app-network:
    driver: bridge