// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { SchemaRetrieveData, SchemaRetrieveResponses, UserCreateData, UserCreateResponses, UserDestroyData, UserDestroyResponses, UserListData, UserListResponses, UserPartialUpdateData, UserPartialUpdateResponses, UserRetrieveData, UserRetrieveResponses, UserUpdateData, UserUpdateResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * OpenApi3 schema for this API. Format can be selected via content negotiation.
 *
 * - YAML: application/vnd.oai.openapi
 * - JSON: application/vnd.oai.openapi+json
 */
export const schemaRetrieve = <ThrowOnError extends boolean = false>(options?: Options<SchemaRetrieveData, ThrowOnError>) => (options?.client ?? client).get<SchemaRetrieveResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }, { scheme: 'basic', type: 'http' }],
    url: '/api/schema/',
    ...options
});

export const userList = <ThrowOnError extends boolean = false>(options?: Options<UserListData, ThrowOnError>) => (options?.client ?? client).get<UserListResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }, { scheme: 'basic', type: 'http' }],
    url: '/api/user/',
    ...options
});

export const userCreate = <ThrowOnError extends boolean = false>(options?: Options<UserCreateData, ThrowOnError>) => (options?.client ?? client).post<UserCreateResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }, { scheme: 'basic', type: 'http' }],
    url: '/api/user/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const userDestroy = <ThrowOnError extends boolean = false>(options: Options<UserDestroyData, ThrowOnError>) => (options.client ?? client).delete<UserDestroyResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }, { scheme: 'basic', type: 'http' }],
    url: '/api/user/{uuid}/',
    ...options
});

export const userRetrieve = <ThrowOnError extends boolean = false>(options: Options<UserRetrieveData, ThrowOnError>) => (options.client ?? client).get<UserRetrieveResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }, { scheme: 'basic', type: 'http' }],
    url: '/api/user/{uuid}/',
    ...options
});

export const userPartialUpdate = <ThrowOnError extends boolean = false>(options: Options<UserPartialUpdateData, ThrowOnError>) => (options.client ?? client).patch<UserPartialUpdateResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }, { scheme: 'basic', type: 'http' }],
    url: '/api/user/{uuid}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const userUpdate = <ThrowOnError extends boolean = false>(options: Options<UserUpdateData, ThrowOnError>) => (options.client ?? client).put<UserUpdateResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }, { scheme: 'basic', type: 'http' }],
    url: '/api/user/{uuid}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
