// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://resohub-backend:8000' | (string & {});
};

export type PatchedUser = {
    readonly uuid?: string;
    username?: string;
    email?: string | null;
    is_staff?: boolean;
    is_superuser?: boolean;
    date_joined?: string;
};

export type User = {
    readonly uuid: string;
    username?: string;
    email?: string | null;
    is_staff?: boolean;
    is_superuser?: boolean;
    date_joined?: string;
};

export type PatchedUserWritable = {
    username?: string;
    email?: string | null;
    is_staff?: boolean;
    is_superuser?: boolean;
    date_joined?: string;
};

export type UserWritable = {
    username?: string;
    email?: string | null;
    is_staff?: boolean;
    is_superuser?: boolean;
    date_joined?: string;
};

export type SchemaRetrieveData = {
    body?: never;
    path?: never;
    query?: {
        format?: 'json' | 'yaml';
        lang?: 'af' | 'ar' | 'ar-dz' | 'ast' | 'az' | 'be' | 'bg' | 'bn' | 'br' | 'bs' | 'ca' | 'ckb' | 'cs' | 'cy' | 'da' | 'de' | 'dsb' | 'el' | 'en' | 'en-au' | 'en-gb' | 'eo' | 'es' | 'es-ar' | 'es-co' | 'es-mx' | 'es-ni' | 'es-ve' | 'et' | 'eu' | 'fa' | 'fi' | 'fr' | 'fy' | 'ga' | 'gd' | 'gl' | 'he' | 'hi' | 'hr' | 'hsb' | 'ht' | 'hu' | 'hy' | 'ia' | 'id' | 'ig' | 'io' | 'is' | 'it' | 'ja' | 'ka' | 'kab' | 'kk' | 'km' | 'kn' | 'ko' | 'ky' | 'lb' | 'lt' | 'lv' | 'mk' | 'ml' | 'mn' | 'mr' | 'ms' | 'my' | 'nb' | 'ne' | 'nl' | 'nn' | 'os' | 'pa' | 'pl' | 'pt' | 'pt-br' | 'ro' | 'ru' | 'sk' | 'sl' | 'sq' | 'sr' | 'sr-latn' | 'sv' | 'sw' | 'ta' | 'te' | 'tg' | 'th' | 'tk' | 'tr' | 'tt' | 'udm' | 'ug' | 'uk' | 'ur' | 'uz' | 'vi' | 'zh-hans' | 'zh-hant';
    };
    url: '/api/schema/';
};

export type SchemaRetrieveResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type SchemaRetrieveResponse = SchemaRetrieveResponses[keyof SchemaRetrieveResponses];

export type UserListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/';
};

export type UserListResponses = {
    200: Array<User>;
};

export type UserListResponse = UserListResponses[keyof UserListResponses];

export type UserCreateData = {
    body?: UserWritable;
    path?: never;
    query?: never;
    url: '/api/user/';
};

export type UserCreateResponses = {
    201: User;
};

export type UserCreateResponse = UserCreateResponses[keyof UserCreateResponses];

export type UserDestroyData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this user.
         */
        uuid: string;
    };
    query?: never;
    url: '/api/user/{uuid}/';
};

export type UserDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type UserDestroyResponse = UserDestroyResponses[keyof UserDestroyResponses];

export type UserRetrieveData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this user.
         */
        uuid: string;
    };
    query?: never;
    url: '/api/user/{uuid}/';
};

export type UserRetrieveResponses = {
    200: User;
};

export type UserRetrieveResponse = UserRetrieveResponses[keyof UserRetrieveResponses];

export type UserPartialUpdateData = {
    body?: PatchedUserWritable;
    path: {
        /**
         * A UUID string identifying this user.
         */
        uuid: string;
    };
    query?: never;
    url: '/api/user/{uuid}/';
};

export type UserPartialUpdateResponses = {
    200: User;
};

export type UserPartialUpdateResponse = UserPartialUpdateResponses[keyof UserPartialUpdateResponses];

export type UserUpdateData = {
    body?: UserWritable;
    path: {
        /**
         * A UUID string identifying this user.
         */
        uuid: string;
    };
    query?: never;
    url: '/api/user/{uuid}/';
};

export type UserUpdateResponses = {
    200: User;
};

export type UserUpdateResponse = UserUpdateResponses[keyof UserUpdateResponses];
