// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://resohub-backend:8000' | (string & {});
};

export type Department = {
    readonly id: number;
    name: string;
    /**
     * 学校
     */
    school: number;
    readonly school_name: string;
};

export type Exam = {
    readonly id: number;
    url: string;
    quarter: number;
    week: number;
    content: string;
    goal: string;
    /**
     * 教科
     */
    subject: number;
    readonly subject_name: string;
    /**
     * 試験グループ
     */
    exam_groupe?: number | null;
    /**
     * ファイル
     */
    file?: number | null;
};

export type ExamGroupe = {
    readonly id: number;
    /**
     * 教科グループ
     */
    subject: number;
    readonly subject_name: string;
    /**
     * 教科グループ
     */
    subject_groupe: number;
};

export type GradeClass = {
    readonly id: number;
    /**
     * クラス
     */
    school_class: number;
    readonly school_class_str: string;
    grade_str?: string;
    /**
     * 補正学年
     */
    grade: number;
    year: number;
};

export type PaginatedDepartmentList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Department>;
};

export type PaginatedExamGroupeList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<ExamGroupe>;
};

export type PaginatedExamList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Exam>;
};

export type PaginatedGradeClassList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<GradeClass>;
};

export type PaginatedSchoolClassList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<SchoolClass>;
};

export type PaginatedSchoolList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<School>;
};

export type PaginatedStudentInfoList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<StudentInfo>;
};

export type PaginatedSubjectGroupeList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<SubjectGroupe>;
};

export type PaginatedSubjectList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Subject>;
};

export type PaginatedSyllabusDepartmentList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<SyllabusDepartment>;
};

export type PaginatedTeacherInfoList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<TeacherInfo>;
};

export type PaginatedUserList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<User>;
};

export type PaginatedUserSettingList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<UserSetting>;
};

export type PatchedDepartment = {
    readonly id?: number;
    name?: string;
    /**
     * 学校
     */
    school?: number;
    readonly school_name?: string;
};

export type PatchedExam = {
    readonly id?: number;
    url?: string;
    quarter?: number;
    week?: number;
    content?: string;
    goal?: string;
    /**
     * 教科
     */
    subject?: number;
    readonly subject_name?: string;
    /**
     * 試験グループ
     */
    exam_groupe?: number | null;
    /**
     * ファイル
     */
    file?: number | null;
};

export type PatchedExamGroupe = {
    readonly id?: number;
    /**
     * 教科グループ
     */
    subject?: number;
    readonly subject_name?: string;
    /**
     * 教科グループ
     */
    subject_groupe?: number;
};

export type PatchedGradeClass = {
    readonly id?: number;
    /**
     * クラス
     */
    school_class?: number;
    readonly school_class_str?: string;
    grade_str?: string;
    /**
     * 補正学年
     */
    grade?: number;
    year?: number;
};

export type PatchedSchool = {
    readonly id?: number;
    url?: string;
    /**
     * 学校名
     */
    name?: string;
    /**
     * 学校コード
     */
    code?: string;
};

export type PatchedSchoolClass = {
    readonly id?: number;
    /**
     * 学部
     */
    department?: number;
    readonly department_name?: string;
    /**
     * シラバス学部
     */
    syllabus_department?: number;
    readonly syllabus_department_name?: string;
    /**
     * 入学年度
     */
    admission_year?: number;
};

export type PatchedStudentInfo = {
    readonly id?: number;
    user?: string;
    readonly user_name?: string;
    student_id?: string;
    school_class?: number | null;
    readonly school_class_str?: string;
};

export type PatchedSubject = {
    readonly id?: number;
    name?: string;
    code?: string;
    subject_type?: string;
    credits?: number;
    teachers_str?: string;
    textbooks?: string;
    url?: string;
    grade_class?: number;
    readonly grade_class_str?: string;
    /**
     * 教科グループ
     */
    subject_groupe?: number | null;
};

export type PatchedSubjectGroupe = {
    readonly id?: number;
    name?: string;
    /**
     * 担当講師陣
     */
    teachers?: Array<number>;
    subjects?: Array<number>;
};

export type PatchedSyllabusDepartment = {
    readonly id?: number;
    url?: string;
    name?: string;
    /**
     * 入学年度
     */
    admission_year?: number;
    code?: string;
    /**
     * 学校
     */
    school?: number;
    readonly school_name?: string;
    department?: number | null;
    readonly department_name?: string;
};

export type PatchedTeacherInfo = {
    readonly id?: number;
    user?: string;
    readonly user_name?: string;
    department?: number | null;
    readonly department_name?: string;
    department_type?: string;
    owner?: boolean;
    subdomain?: string;
    /**
     * 担当教科
     */
    subjects?: Array<number>;
};

export type PatchedUser = {
    readonly uuid?: string;
    username?: string;
    email?: string | null;
    name?: string;
    /**
     * 役割
     */
    role?: RoleEnum;
    is_staff?: boolean;
    is_superuser?: boolean;
    is_active?: boolean;
    date_joined?: string;
};

export type PatchedUserSetting = {
    readonly id?: number;
    user?: string;
    readonly user_name?: string;
};

/**
 * * `student` - 生徒
 * * `teacher` - 教師
 * * `staff` - 管理者
 * * `system` - System
 * * `student_affairs` - 学生課
 * * `unregistered` - 未登録
 */
export type RoleEnum = 'student' | 'teacher' | 'staff' | 'system' | 'student_affairs' | 'unregistered';

export type School = {
    readonly id: number;
    url: string;
    /**
     * 学校名
     */
    name: string;
    /**
     * 学校コード
     */
    code: string;
};

export type SchoolClass = {
    readonly id: number;
    /**
     * 学部
     */
    department: number;
    readonly department_name: string;
    /**
     * シラバス学部
     */
    syllabus_department: number;
    readonly syllabus_department_name: string;
    /**
     * 入学年度
     */
    admission_year: number;
};

export type StudentInfo = {
    readonly id: number;
    user: string;
    readonly user_name: string;
    student_id: string;
    school_class?: number | null;
    readonly school_class_str: string;
};

export type Subject = {
    readonly id: number;
    name: string;
    code: string;
    subject_type: string;
    credits: number;
    teachers_str: string;
    textbooks: string;
    url: string;
    grade_class: number;
    readonly grade_class_str: string;
    /**
     * 教科グループ
     */
    subject_groupe?: number | null;
};

export type SubjectGroupe = {
    readonly id: number;
    name: string;
    /**
     * 担当講師陣
     */
    teachers: Array<number>;
    subjects: Array<number>;
};

export type SyllabusDepartment = {
    readonly id: number;
    url: string;
    name: string;
    /**
     * 入学年度
     */
    admission_year: number;
    code: string;
    /**
     * 学校
     */
    school: number;
    readonly school_name: string;
    department?: number | null;
    readonly department_name: string;
};

export type TeacherInfo = {
    readonly id: number;
    user: string;
    readonly user_name: string;
    department?: number | null;
    readonly department_name: string;
    department_type?: string;
    owner?: boolean;
    subdomain: string;
    /**
     * 担当教科
     */
    subjects: Array<number>;
};

export type User = {
    readonly uuid: string;
    username?: string;
    email?: string | null;
    name?: string;
    /**
     * 役割
     */
    role?: RoleEnum;
    is_staff?: boolean;
    is_superuser?: boolean;
    is_active?: boolean;
    date_joined?: string;
};

export type UserSetting = {
    readonly id: number;
    user: string;
    readonly user_name: string;
};

export type DepartmentWritable = {
    name: string;
    /**
     * 学校
     */
    school: number;
};

export type ExamWritable = {
    url: string;
    quarter: number;
    week: number;
    content: string;
    goal: string;
    /**
     * 教科
     */
    subject: number;
    /**
     * 試験グループ
     */
    exam_groupe?: number | null;
    /**
     * ファイル
     */
    file?: number | null;
};

export type ExamGroupeWritable = {
    /**
     * 教科グループ
     */
    subject: number;
    /**
     * 教科グループ
     */
    subject_groupe: number;
};

export type GradeClassWritable = {
    /**
     * クラス
     */
    school_class: number;
    grade_str?: string;
    /**
     * 補正学年
     */
    grade: number;
    year: number;
};

export type PaginatedDepartmentListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<DepartmentWritable>;
};

export type PaginatedExamGroupeListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<ExamGroupeWritable>;
};

export type PaginatedExamListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<ExamWritable>;
};

export type PaginatedGradeClassListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<GradeClassWritable>;
};

export type PaginatedSchoolClassListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<SchoolClassWritable>;
};

export type PaginatedSchoolListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<SchoolWritable>;
};

export type PaginatedStudentInfoListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<StudentInfoWritable>;
};

export type PaginatedSubjectGroupeListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<SubjectGroupeWritable>;
};

export type PaginatedSubjectListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<SubjectWritable>;
};

export type PaginatedSyllabusDepartmentListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<SyllabusDepartmentWritable>;
};

export type PaginatedTeacherInfoListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<TeacherInfoWritable>;
};

export type PaginatedUserListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<UserWritable>;
};

export type PaginatedUserSettingListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<UserSettingWritable>;
};

export type PatchedDepartmentWritable = {
    name?: string;
    /**
     * 学校
     */
    school?: number;
};

export type PatchedExamWritable = {
    url?: string;
    quarter?: number;
    week?: number;
    content?: string;
    goal?: string;
    /**
     * 教科
     */
    subject?: number;
    /**
     * 試験グループ
     */
    exam_groupe?: number | null;
    /**
     * ファイル
     */
    file?: number | null;
};

export type PatchedExamGroupeWritable = {
    /**
     * 教科グループ
     */
    subject?: number;
    /**
     * 教科グループ
     */
    subject_groupe?: number;
};

export type PatchedGradeClassWritable = {
    /**
     * クラス
     */
    school_class?: number;
    grade_str?: string;
    /**
     * 補正学年
     */
    grade?: number;
    year?: number;
};

export type PatchedSchoolWritable = {
    url?: string;
    /**
     * 学校名
     */
    name?: string;
    /**
     * 学校コード
     */
    code?: string;
};

export type PatchedSchoolClassWritable = {
    /**
     * 学部
     */
    department?: number;
    /**
     * シラバス学部
     */
    syllabus_department?: number;
    /**
     * 入学年度
     */
    admission_year?: number;
};

export type PatchedStudentInfoWritable = {
    user?: string;
    student_id?: string;
    school_class?: number | null;
};

export type PatchedSubjectWritable = {
    name?: string;
    code?: string;
    subject_type?: string;
    credits?: number;
    teachers_str?: string;
    textbooks?: string;
    url?: string;
    grade_class?: number;
    /**
     * 教科グループ
     */
    subject_groupe?: number | null;
};

export type PatchedSubjectGroupeWritable = {
    name?: string;
    /**
     * 担当講師陣
     */
    teachers?: Array<number>;
    subjects?: Array<number>;
};

export type PatchedSyllabusDepartmentWritable = {
    url?: string;
    name?: string;
    /**
     * 入学年度
     */
    admission_year?: number;
    code?: string;
    /**
     * 学校
     */
    school?: number;
    department?: number | null;
};

export type PatchedTeacherInfoWritable = {
    user?: string;
    department?: number | null;
    department_type?: string;
    owner?: boolean;
    subdomain?: string;
    /**
     * 担当教科
     */
    subjects?: Array<number>;
};

export type PatchedUserWritable = {
    username?: string;
    email?: string | null;
    name?: string;
    /**
     * 役割
     */
    role?: RoleEnum;
    is_staff?: boolean;
    is_superuser?: boolean;
    is_active?: boolean;
    date_joined?: string;
};

export type PatchedUserSettingWritable = {
    user?: string;
};

export type SchoolWritable = {
    url: string;
    /**
     * 学校名
     */
    name: string;
    /**
     * 学校コード
     */
    code: string;
};

export type SchoolClassWritable = {
    /**
     * 学部
     */
    department: number;
    /**
     * シラバス学部
     */
    syllabus_department: number;
    /**
     * 入学年度
     */
    admission_year: number;
};

export type StudentInfoWritable = {
    user: string;
    student_id: string;
    school_class?: number | null;
};

export type SubjectWritable = {
    name: string;
    code: string;
    subject_type: string;
    credits: number;
    teachers_str: string;
    textbooks: string;
    url: string;
    grade_class: number;
    /**
     * 教科グループ
     */
    subject_groupe?: number | null;
};

export type SubjectGroupeWritable = {
    name: string;
    /**
     * 担当講師陣
     */
    teachers: Array<number>;
    subjects: Array<number>;
};

export type SyllabusDepartmentWritable = {
    url: string;
    name: string;
    /**
     * 入学年度
     */
    admission_year: number;
    code: string;
    /**
     * 学校
     */
    school: number;
    department?: number | null;
};

export type TeacherInfoWritable = {
    user: string;
    department?: number | null;
    department_type?: string;
    owner?: boolean;
    subdomain: string;
    /**
     * 担当教科
     */
    subjects: Array<number>;
};

export type UserWritable = {
    username?: string;
    email?: string | null;
    name?: string;
    /**
     * 役割
     */
    role?: RoleEnum;
    is_staff?: boolean;
    is_superuser?: boolean;
    is_active?: boolean;
    date_joined?: string;
};

export type UserSettingWritable = {
    user: string;
};

export type DepartmentListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
    };
    url: '/api/department/';
};

export type DepartmentListResponses = {
    200: PaginatedDepartmentList;
};

export type DepartmentListResponse = DepartmentListResponses[keyof DepartmentListResponses];

export type DepartmentCreateData = {
    body: DepartmentWritable;
    path?: never;
    query?: never;
    url: '/api/department/';
};

export type DepartmentCreateResponses = {
    201: Department;
};

export type DepartmentCreateResponse = DepartmentCreateResponses[keyof DepartmentCreateResponses];

export type DepartmentDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this 学部.
         */
        id: number;
    };
    query?: never;
    url: '/api/department/{id}/';
};

export type DepartmentDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type DepartmentDestroyResponse = DepartmentDestroyResponses[keyof DepartmentDestroyResponses];

export type DepartmentRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this 学部.
         */
        id: number;
    };
    query?: never;
    url: '/api/department/{id}/';
};

export type DepartmentRetrieveResponses = {
    200: Department;
};

export type DepartmentRetrieveResponse = DepartmentRetrieveResponses[keyof DepartmentRetrieveResponses];

export type DepartmentPartialUpdateData = {
    body?: PatchedDepartmentWritable;
    path: {
        /**
         * A unique integer value identifying this 学部.
         */
        id: number;
    };
    query?: never;
    url: '/api/department/{id}/';
};

export type DepartmentPartialUpdateResponses = {
    200: Department;
};

export type DepartmentPartialUpdateResponse = DepartmentPartialUpdateResponses[keyof DepartmentPartialUpdateResponses];

export type DepartmentUpdateData = {
    body: DepartmentWritable;
    path: {
        /**
         * A unique integer value identifying this 学部.
         */
        id: number;
    };
    query?: never;
    url: '/api/department/{id}/';
};

export type DepartmentUpdateResponses = {
    200: Department;
};

export type DepartmentUpdateResponse = DepartmentUpdateResponses[keyof DepartmentUpdateResponses];

export type ExamListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
    };
    url: '/api/exam/';
};

export type ExamListResponses = {
    200: PaginatedExamList;
};

export type ExamListResponse = ExamListResponses[keyof ExamListResponses];

export type ExamCreateData = {
    body: ExamWritable;
    path?: never;
    query?: never;
    url: '/api/exam/';
};

export type ExamCreateResponses = {
    201: Exam;
};

export type ExamCreateResponse = ExamCreateResponses[keyof ExamCreateResponses];

export type ExamGroupeListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
    };
    url: '/api/exam-groupe/';
};

export type ExamGroupeListResponses = {
    200: PaginatedExamGroupeList;
};

export type ExamGroupeListResponse = ExamGroupeListResponses[keyof ExamGroupeListResponses];

export type ExamGroupeCreateData = {
    body: ExamGroupeWritable;
    path?: never;
    query?: never;
    url: '/api/exam-groupe/';
};

export type ExamGroupeCreateResponses = {
    201: ExamGroupe;
};

export type ExamGroupeCreateResponse = ExamGroupeCreateResponses[keyof ExamGroupeCreateResponses];

export type ExamGroupeDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this 試験グループ.
         */
        id: number;
    };
    query?: never;
    url: '/api/exam-groupe/{id}/';
};

export type ExamGroupeDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type ExamGroupeDestroyResponse = ExamGroupeDestroyResponses[keyof ExamGroupeDestroyResponses];

export type ExamGroupeRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this 試験グループ.
         */
        id: number;
    };
    query?: never;
    url: '/api/exam-groupe/{id}/';
};

export type ExamGroupeRetrieveResponses = {
    200: ExamGroupe;
};

export type ExamGroupeRetrieveResponse = ExamGroupeRetrieveResponses[keyof ExamGroupeRetrieveResponses];

export type ExamGroupePartialUpdateData = {
    body?: PatchedExamGroupeWritable;
    path: {
        /**
         * A unique integer value identifying this 試験グループ.
         */
        id: number;
    };
    query?: never;
    url: '/api/exam-groupe/{id}/';
};

export type ExamGroupePartialUpdateResponses = {
    200: ExamGroupe;
};

export type ExamGroupePartialUpdateResponse = ExamGroupePartialUpdateResponses[keyof ExamGroupePartialUpdateResponses];

export type ExamGroupeUpdateData = {
    body: ExamGroupeWritable;
    path: {
        /**
         * A unique integer value identifying this 試験グループ.
         */
        id: number;
    };
    query?: never;
    url: '/api/exam-groupe/{id}/';
};

export type ExamGroupeUpdateResponses = {
    200: ExamGroupe;
};

export type ExamGroupeUpdateResponse = ExamGroupeUpdateResponses[keyof ExamGroupeUpdateResponses];

export type ExamDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this 試験.
         */
        id: number;
    };
    query?: never;
    url: '/api/exam/{id}/';
};

export type ExamDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type ExamDestroyResponse = ExamDestroyResponses[keyof ExamDestroyResponses];

export type ExamRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this 試験.
         */
        id: number;
    };
    query?: never;
    url: '/api/exam/{id}/';
};

export type ExamRetrieveResponses = {
    200: Exam;
};

export type ExamRetrieveResponse = ExamRetrieveResponses[keyof ExamRetrieveResponses];

export type ExamPartialUpdateData = {
    body?: PatchedExamWritable;
    path: {
        /**
         * A unique integer value identifying this 試験.
         */
        id: number;
    };
    query?: never;
    url: '/api/exam/{id}/';
};

export type ExamPartialUpdateResponses = {
    200: Exam;
};

export type ExamPartialUpdateResponse = ExamPartialUpdateResponses[keyof ExamPartialUpdateResponses];

export type ExamUpdateData = {
    body: ExamWritable;
    path: {
        /**
         * A unique integer value identifying this 試験.
         */
        id: number;
    };
    query?: never;
    url: '/api/exam/{id}/';
};

export type ExamUpdateResponses = {
    200: Exam;
};

export type ExamUpdateResponse = ExamUpdateResponses[keyof ExamUpdateResponses];

export type GradeClassListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
    };
    url: '/api/grade-class/';
};

export type GradeClassListResponses = {
    200: PaginatedGradeClassList;
};

export type GradeClassListResponse = GradeClassListResponses[keyof GradeClassListResponses];

export type GradeClassCreateData = {
    body: GradeClassWritable;
    path?: never;
    query?: never;
    url: '/api/grade-class/';
};

export type GradeClassCreateResponses = {
    201: GradeClass;
};

export type GradeClassCreateResponse = GradeClassCreateResponses[keyof GradeClassCreateResponses];

export type GradeClassDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this grade class.
         */
        id: number;
    };
    query?: never;
    url: '/api/grade-class/{id}/';
};

export type GradeClassDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type GradeClassDestroyResponse = GradeClassDestroyResponses[keyof GradeClassDestroyResponses];

export type GradeClassRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this grade class.
         */
        id: number;
    };
    query?: never;
    url: '/api/grade-class/{id}/';
};

export type GradeClassRetrieveResponses = {
    200: GradeClass;
};

export type GradeClassRetrieveResponse = GradeClassRetrieveResponses[keyof GradeClassRetrieveResponses];

export type GradeClassPartialUpdateData = {
    body?: PatchedGradeClassWritable;
    path: {
        /**
         * A unique integer value identifying this grade class.
         */
        id: number;
    };
    query?: never;
    url: '/api/grade-class/{id}/';
};

export type GradeClassPartialUpdateResponses = {
    200: GradeClass;
};

export type GradeClassPartialUpdateResponse = GradeClassPartialUpdateResponses[keyof GradeClassPartialUpdateResponses];

export type GradeClassUpdateData = {
    body: GradeClassWritable;
    path: {
        /**
         * A unique integer value identifying this grade class.
         */
        id: number;
    };
    query?: never;
    url: '/api/grade-class/{id}/';
};

export type GradeClassUpdateResponses = {
    200: GradeClass;
};

export type GradeClassUpdateResponse = GradeClassUpdateResponses[keyof GradeClassUpdateResponses];

export type SchemaRetrieveData = {
    body?: never;
    path?: never;
    query?: {
        format?: 'json' | 'yaml';
        lang?: 'af' | 'ar' | 'ar-dz' | 'ast' | 'az' | 'be' | 'bg' | 'bn' | 'br' | 'bs' | 'ca' | 'ckb' | 'cs' | 'cy' | 'da' | 'de' | 'dsb' | 'el' | 'en' | 'en-au' | 'en-gb' | 'eo' | 'es' | 'es-ar' | 'es-co' | 'es-mx' | 'es-ni' | 'es-ve' | 'et' | 'eu' | 'fa' | 'fi' | 'fr' | 'fy' | 'ga' | 'gd' | 'gl' | 'he' | 'hi' | 'hr' | 'hsb' | 'ht' | 'hu' | 'hy' | 'ia' | 'id' | 'ig' | 'io' | 'is' | 'it' | 'ja' | 'ka' | 'kab' | 'kk' | 'km' | 'kn' | 'ko' | 'ky' | 'lb' | 'lt' | 'lv' | 'mk' | 'ml' | 'mn' | 'mr' | 'ms' | 'my' | 'nb' | 'ne' | 'nl' | 'nn' | 'os' | 'pa' | 'pl' | 'pt' | 'pt-br' | 'ro' | 'ru' | 'sk' | 'sl' | 'sq' | 'sr' | 'sr-latn' | 'sv' | 'sw' | 'ta' | 'te' | 'tg' | 'th' | 'tk' | 'tr' | 'tt' | 'udm' | 'ug' | 'uk' | 'ur' | 'uz' | 'vi' | 'zh-hans' | 'zh-hant';
    };
    url: '/api/schema/';
};

export type SchemaRetrieveResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type SchemaRetrieveResponse = SchemaRetrieveResponses[keyof SchemaRetrieveResponses];

export type SchoolListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
    };
    url: '/api/school/';
};

export type SchoolListResponses = {
    200: PaginatedSchoolList;
};

export type SchoolListResponse = SchoolListResponses[keyof SchoolListResponses];

export type SchoolCreateData = {
    body: SchoolWritable;
    path?: never;
    query?: never;
    url: '/api/school/';
};

export type SchoolCreateResponses = {
    201: School;
};

export type SchoolCreateResponse = SchoolCreateResponses[keyof SchoolCreateResponses];

export type SchoolClassListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
    };
    url: '/api/school-class/';
};

export type SchoolClassListResponses = {
    200: PaginatedSchoolClassList;
};

export type SchoolClassListResponse = SchoolClassListResponses[keyof SchoolClassListResponses];

export type SchoolClassCreateData = {
    body: SchoolClassWritable;
    path?: never;
    query?: never;
    url: '/api/school-class/';
};

export type SchoolClassCreateResponses = {
    201: SchoolClass;
};

export type SchoolClassCreateResponse = SchoolClassCreateResponses[keyof SchoolClassCreateResponses];

export type SchoolClassDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this クラス.
         */
        id: number;
    };
    query?: never;
    url: '/api/school-class/{id}/';
};

export type SchoolClassDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type SchoolClassDestroyResponse = SchoolClassDestroyResponses[keyof SchoolClassDestroyResponses];

export type SchoolClassRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this クラス.
         */
        id: number;
    };
    query?: never;
    url: '/api/school-class/{id}/';
};

export type SchoolClassRetrieveResponses = {
    200: SchoolClass;
};

export type SchoolClassRetrieveResponse = SchoolClassRetrieveResponses[keyof SchoolClassRetrieveResponses];

export type SchoolClassPartialUpdateData = {
    body?: PatchedSchoolClassWritable;
    path: {
        /**
         * A unique integer value identifying this クラス.
         */
        id: number;
    };
    query?: never;
    url: '/api/school-class/{id}/';
};

export type SchoolClassPartialUpdateResponses = {
    200: SchoolClass;
};

export type SchoolClassPartialUpdateResponse = SchoolClassPartialUpdateResponses[keyof SchoolClassPartialUpdateResponses];

export type SchoolClassUpdateData = {
    body: SchoolClassWritable;
    path: {
        /**
         * A unique integer value identifying this クラス.
         */
        id: number;
    };
    query?: never;
    url: '/api/school-class/{id}/';
};

export type SchoolClassUpdateResponses = {
    200: SchoolClass;
};

export type SchoolClassUpdateResponse = SchoolClassUpdateResponses[keyof SchoolClassUpdateResponses];

export type SchoolDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this 学校.
         */
        id: number;
    };
    query?: never;
    url: '/api/school/{id}/';
};

export type SchoolDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type SchoolDestroyResponse = SchoolDestroyResponses[keyof SchoolDestroyResponses];

export type SchoolRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this 学校.
         */
        id: number;
    };
    query?: never;
    url: '/api/school/{id}/';
};

export type SchoolRetrieveResponses = {
    200: School;
};

export type SchoolRetrieveResponse = SchoolRetrieveResponses[keyof SchoolRetrieveResponses];

export type SchoolPartialUpdateData = {
    body?: PatchedSchoolWritable;
    path: {
        /**
         * A unique integer value identifying this 学校.
         */
        id: number;
    };
    query?: never;
    url: '/api/school/{id}/';
};

export type SchoolPartialUpdateResponses = {
    200: School;
};

export type SchoolPartialUpdateResponse = SchoolPartialUpdateResponses[keyof SchoolPartialUpdateResponses];

export type SchoolUpdateData = {
    body: SchoolWritable;
    path: {
        /**
         * A unique integer value identifying this 学校.
         */
        id: number;
    };
    query?: never;
    url: '/api/school/{id}/';
};

export type SchoolUpdateResponses = {
    200: School;
};

export type SchoolUpdateResponse = SchoolUpdateResponses[keyof SchoolUpdateResponses];

export type StudentInfoListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
    };
    url: '/api/student-info/';
};

export type StudentInfoListResponses = {
    200: PaginatedStudentInfoList;
};

export type StudentInfoListResponse = StudentInfoListResponses[keyof StudentInfoListResponses];

export type StudentInfoCreateData = {
    body: StudentInfoWritable;
    path?: never;
    query?: never;
    url: '/api/student-info/';
};

export type StudentInfoCreateResponses = {
    201: StudentInfo;
};

export type StudentInfoCreateResponse = StudentInfoCreateResponses[keyof StudentInfoCreateResponses];

export type StudentInfoDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this 生徒情報.
         */
        id: number;
    };
    query?: never;
    url: '/api/student-info/{id}/';
};

export type StudentInfoDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type StudentInfoDestroyResponse = StudentInfoDestroyResponses[keyof StudentInfoDestroyResponses];

export type StudentInfoRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this 生徒情報.
         */
        id: number;
    };
    query?: never;
    url: '/api/student-info/{id}/';
};

export type StudentInfoRetrieveResponses = {
    200: StudentInfo;
};

export type StudentInfoRetrieveResponse = StudentInfoRetrieveResponses[keyof StudentInfoRetrieveResponses];

export type StudentInfoPartialUpdateData = {
    body?: PatchedStudentInfoWritable;
    path: {
        /**
         * A unique integer value identifying this 生徒情報.
         */
        id: number;
    };
    query?: never;
    url: '/api/student-info/{id}/';
};

export type StudentInfoPartialUpdateResponses = {
    200: StudentInfo;
};

export type StudentInfoPartialUpdateResponse = StudentInfoPartialUpdateResponses[keyof StudentInfoPartialUpdateResponses];

export type StudentInfoUpdateData = {
    body: StudentInfoWritable;
    path: {
        /**
         * A unique integer value identifying this 生徒情報.
         */
        id: number;
    };
    query?: never;
    url: '/api/student-info/{id}/';
};

export type StudentInfoUpdateResponses = {
    200: StudentInfo;
};

export type StudentInfoUpdateResponse = StudentInfoUpdateResponses[keyof StudentInfoUpdateResponses];

export type SubjectListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
    };
    url: '/api/subject/';
};

export type SubjectListResponses = {
    200: PaginatedSubjectList;
};

export type SubjectListResponse = SubjectListResponses[keyof SubjectListResponses];

export type SubjectCreateData = {
    body: SubjectWritable;
    path?: never;
    query?: never;
    url: '/api/subject/';
};

export type SubjectCreateResponses = {
    201: Subject;
};

export type SubjectCreateResponse = SubjectCreateResponses[keyof SubjectCreateResponses];

export type SubjectGroupeListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
    };
    url: '/api/subject-groupe/';
};

export type SubjectGroupeListResponses = {
    200: PaginatedSubjectGroupeList;
};

export type SubjectGroupeListResponse = SubjectGroupeListResponses[keyof SubjectGroupeListResponses];

export type SubjectGroupeCreateData = {
    body: SubjectGroupeWritable;
    path?: never;
    query?: never;
    url: '/api/subject-groupe/';
};

export type SubjectGroupeCreateResponses = {
    201: SubjectGroupe;
};

export type SubjectGroupeCreateResponse = SubjectGroupeCreateResponses[keyof SubjectGroupeCreateResponses];

export type SubjectGroupeDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this 教科グループ.
         */
        id: number;
    };
    query?: never;
    url: '/api/subject-groupe/{id}/';
};

export type SubjectGroupeDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type SubjectGroupeDestroyResponse = SubjectGroupeDestroyResponses[keyof SubjectGroupeDestroyResponses];

export type SubjectGroupeRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this 教科グループ.
         */
        id: number;
    };
    query?: never;
    url: '/api/subject-groupe/{id}/';
};

export type SubjectGroupeRetrieveResponses = {
    200: SubjectGroupe;
};

export type SubjectGroupeRetrieveResponse = SubjectGroupeRetrieveResponses[keyof SubjectGroupeRetrieveResponses];

export type SubjectGroupePartialUpdateData = {
    body?: PatchedSubjectGroupeWritable;
    path: {
        /**
         * A unique integer value identifying this 教科グループ.
         */
        id: number;
    };
    query?: never;
    url: '/api/subject-groupe/{id}/';
};

export type SubjectGroupePartialUpdateResponses = {
    200: SubjectGroupe;
};

export type SubjectGroupePartialUpdateResponse = SubjectGroupePartialUpdateResponses[keyof SubjectGroupePartialUpdateResponses];

export type SubjectGroupeUpdateData = {
    body: SubjectGroupeWritable;
    path: {
        /**
         * A unique integer value identifying this 教科グループ.
         */
        id: number;
    };
    query?: never;
    url: '/api/subject-groupe/{id}/';
};

export type SubjectGroupeUpdateResponses = {
    200: SubjectGroupe;
};

export type SubjectGroupeUpdateResponse = SubjectGroupeUpdateResponses[keyof SubjectGroupeUpdateResponses];

export type SubjectDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this 教科.
         */
        id: number;
    };
    query?: never;
    url: '/api/subject/{id}/';
};

export type SubjectDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type SubjectDestroyResponse = SubjectDestroyResponses[keyof SubjectDestroyResponses];

export type SubjectRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this 教科.
         */
        id: number;
    };
    query?: never;
    url: '/api/subject/{id}/';
};

export type SubjectRetrieveResponses = {
    200: Subject;
};

export type SubjectRetrieveResponse = SubjectRetrieveResponses[keyof SubjectRetrieveResponses];

export type SubjectPartialUpdateData = {
    body?: PatchedSubjectWritable;
    path: {
        /**
         * A unique integer value identifying this 教科.
         */
        id: number;
    };
    query?: never;
    url: '/api/subject/{id}/';
};

export type SubjectPartialUpdateResponses = {
    200: Subject;
};

export type SubjectPartialUpdateResponse = SubjectPartialUpdateResponses[keyof SubjectPartialUpdateResponses];

export type SubjectUpdateData = {
    body: SubjectWritable;
    path: {
        /**
         * A unique integer value identifying this 教科.
         */
        id: number;
    };
    query?: never;
    url: '/api/subject/{id}/';
};

export type SubjectUpdateResponses = {
    200: Subject;
};

export type SubjectUpdateResponse = SubjectUpdateResponses[keyof SubjectUpdateResponses];

export type SyllabusDepartmentListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
    };
    url: '/api/syllabus-department/';
};

export type SyllabusDepartmentListResponses = {
    200: PaginatedSyllabusDepartmentList;
};

export type SyllabusDepartmentListResponse = SyllabusDepartmentListResponses[keyof SyllabusDepartmentListResponses];

export type SyllabusDepartmentCreateData = {
    body: SyllabusDepartmentWritable;
    path?: never;
    query?: never;
    url: '/api/syllabus-department/';
};

export type SyllabusDepartmentCreateResponses = {
    201: SyllabusDepartment;
};

export type SyllabusDepartmentCreateResponse = SyllabusDepartmentCreateResponses[keyof SyllabusDepartmentCreateResponses];

export type SyllabusDepartmentDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this syllabus department.
         */
        id: number;
    };
    query?: never;
    url: '/api/syllabus-department/{id}/';
};

export type SyllabusDepartmentDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type SyllabusDepartmentDestroyResponse = SyllabusDepartmentDestroyResponses[keyof SyllabusDepartmentDestroyResponses];

export type SyllabusDepartmentRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this syllabus department.
         */
        id: number;
    };
    query?: never;
    url: '/api/syllabus-department/{id}/';
};

export type SyllabusDepartmentRetrieveResponses = {
    200: SyllabusDepartment;
};

export type SyllabusDepartmentRetrieveResponse = SyllabusDepartmentRetrieveResponses[keyof SyllabusDepartmentRetrieveResponses];

export type SyllabusDepartmentPartialUpdateData = {
    body?: PatchedSyllabusDepartmentWritable;
    path: {
        /**
         * A unique integer value identifying this syllabus department.
         */
        id: number;
    };
    query?: never;
    url: '/api/syllabus-department/{id}/';
};

export type SyllabusDepartmentPartialUpdateResponses = {
    200: SyllabusDepartment;
};

export type SyllabusDepartmentPartialUpdateResponse = SyllabusDepartmentPartialUpdateResponses[keyof SyllabusDepartmentPartialUpdateResponses];

export type SyllabusDepartmentUpdateData = {
    body: SyllabusDepartmentWritable;
    path: {
        /**
         * A unique integer value identifying this syllabus department.
         */
        id: number;
    };
    query?: never;
    url: '/api/syllabus-department/{id}/';
};

export type SyllabusDepartmentUpdateResponses = {
    200: SyllabusDepartment;
};

export type SyllabusDepartmentUpdateResponse = SyllabusDepartmentUpdateResponses[keyof SyllabusDepartmentUpdateResponses];

export type TeacherInfoListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
    };
    url: '/api/teacher-info/';
};

export type TeacherInfoListResponses = {
    200: PaginatedTeacherInfoList;
};

export type TeacherInfoListResponse = TeacherInfoListResponses[keyof TeacherInfoListResponses];

export type TeacherInfoCreateData = {
    body: TeacherInfoWritable;
    path?: never;
    query?: never;
    url: '/api/teacher-info/';
};

export type TeacherInfoCreateResponses = {
    201: TeacherInfo;
};

export type TeacherInfoCreateResponse = TeacherInfoCreateResponses[keyof TeacherInfoCreateResponses];

export type TeacherInfoDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this 教師情報.
         */
        id: number;
    };
    query?: never;
    url: '/api/teacher-info/{id}/';
};

export type TeacherInfoDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type TeacherInfoDestroyResponse = TeacherInfoDestroyResponses[keyof TeacherInfoDestroyResponses];

export type TeacherInfoRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this 教師情報.
         */
        id: number;
    };
    query?: never;
    url: '/api/teacher-info/{id}/';
};

export type TeacherInfoRetrieveResponses = {
    200: TeacherInfo;
};

export type TeacherInfoRetrieveResponse = TeacherInfoRetrieveResponses[keyof TeacherInfoRetrieveResponses];

export type TeacherInfoPartialUpdateData = {
    body?: PatchedTeacherInfoWritable;
    path: {
        /**
         * A unique integer value identifying this 教師情報.
         */
        id: number;
    };
    query?: never;
    url: '/api/teacher-info/{id}/';
};

export type TeacherInfoPartialUpdateResponses = {
    200: TeacherInfo;
};

export type TeacherInfoPartialUpdateResponse = TeacherInfoPartialUpdateResponses[keyof TeacherInfoPartialUpdateResponses];

export type TeacherInfoUpdateData = {
    body: TeacherInfoWritable;
    path: {
        /**
         * A unique integer value identifying this 教師情報.
         */
        id: number;
    };
    query?: never;
    url: '/api/teacher-info/{id}/';
};

export type TeacherInfoUpdateResponses = {
    200: TeacherInfo;
};

export type TeacherInfoUpdateResponse = TeacherInfoUpdateResponses[keyof TeacherInfoUpdateResponses];

export type UserListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
    };
    url: '/api/user/';
};

export type UserListResponses = {
    200: PaginatedUserList;
};

export type UserListResponse = UserListResponses[keyof UserListResponses];

export type UserCreateData = {
    body?: UserWritable;
    path?: never;
    query?: never;
    url: '/api/user/';
};

export type UserCreateResponses = {
    201: User;
};

export type UserCreateResponse = UserCreateResponses[keyof UserCreateResponses];

export type UserSettingListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
    };
    url: '/api/user-setting/';
};

export type UserSettingListResponses = {
    200: PaginatedUserSettingList;
};

export type UserSettingListResponse = UserSettingListResponses[keyof UserSettingListResponses];

export type UserSettingCreateData = {
    body: UserSettingWritable;
    path?: never;
    query?: never;
    url: '/api/user-setting/';
};

export type UserSettingCreateResponses = {
    201: UserSetting;
};

export type UserSettingCreateResponse = UserSettingCreateResponses[keyof UserSettingCreateResponses];

export type UserSettingDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this ユーザー設定.
         */
        id: number;
    };
    query?: never;
    url: '/api/user-setting/{id}/';
};

export type UserSettingDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type UserSettingDestroyResponse = UserSettingDestroyResponses[keyof UserSettingDestroyResponses];

export type UserSettingRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this ユーザー設定.
         */
        id: number;
    };
    query?: never;
    url: '/api/user-setting/{id}/';
};

export type UserSettingRetrieveResponses = {
    200: UserSetting;
};

export type UserSettingRetrieveResponse = UserSettingRetrieveResponses[keyof UserSettingRetrieveResponses];

export type UserSettingPartialUpdateData = {
    body?: PatchedUserSettingWritable;
    path: {
        /**
         * A unique integer value identifying this ユーザー設定.
         */
        id: number;
    };
    query?: never;
    url: '/api/user-setting/{id}/';
};

export type UserSettingPartialUpdateResponses = {
    200: UserSetting;
};

export type UserSettingPartialUpdateResponse = UserSettingPartialUpdateResponses[keyof UserSettingPartialUpdateResponses];

export type UserSettingUpdateData = {
    body: UserSettingWritable;
    path: {
        /**
         * A unique integer value identifying this ユーザー設定.
         */
        id: number;
    };
    query?: never;
    url: '/api/user-setting/{id}/';
};

export type UserSettingUpdateResponses = {
    200: UserSetting;
};

export type UserSettingUpdateResponse = UserSettingUpdateResponses[keyof UserSettingUpdateResponses];

export type UserDestroyData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this user.
         */
        uuid: string;
    };
    query?: never;
    url: '/api/user/{uuid}/';
};

export type UserDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type UserDestroyResponse = UserDestroyResponses[keyof UserDestroyResponses];

export type UserRetrieveData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this user.
         */
        uuid: string;
    };
    query?: never;
    url: '/api/user/{uuid}/';
};

export type UserRetrieveResponses = {
    200: User;
};

export type UserRetrieveResponse = UserRetrieveResponses[keyof UserRetrieveResponses];

export type UserPartialUpdateData = {
    body?: PatchedUserWritable;
    path: {
        /**
         * A UUID string identifying this user.
         */
        uuid: string;
    };
    query?: never;
    url: '/api/user/{uuid}/';
};

export type UserPartialUpdateResponses = {
    200: User;
};

export type UserPartialUpdateResponse = UserPartialUpdateResponses[keyof UserPartialUpdateResponses];

export type UserUpdateData = {
    body?: UserWritable;
    path: {
        /**
         * A UUID string identifying this user.
         */
        uuid: string;
    };
    query?: never;
    url: '/api/user/{uuid}/';
};

export type UserUpdateResponses = {
    200: User;
};

export type UserUpdateResponse = UserUpdateResponses[keyof UserUpdateResponses];
