# Generated by Django 6.0.4 on 2026-04-13 06:18

import content.models.user
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "学部",
                "verbose_name_plural": "学部",
                "db_table": "department",
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=200)),
                ("quarter", models.PositiveIntegerField()),
                ("week", models.PositiveIntegerField()),
                ("content", models.CharField(max_length=500)),
                ("goal", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "試験",
                "verbose_name_plural": "試験",
                "db_table": "exam",
            },
        ),
        migrations.CreateModel(
            name="ExamGroupe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "試験グループ",
                "verbose_name_plural": "試験グループ",
                "db_table": "exam_groupe",
            },
        ),
        migrations.CreateModel(
            name="GradeClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade_str", models.CharField(default="学年", max_length=10)),
                ("grade", models.PositiveIntegerField(verbose_name="補正学年")),
                ("year", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=200, verbose_name="学校名")),
                ("code", models.CharField(max_length=50, verbose_name="学校コード")),
            ],
            options={
                "verbose_name": "学校",
                "verbose_name_plural": "学校",
                "db_table": "school",
            },
        ),
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admission_year", models.IntegerField(verbose_name="入学年度")),
            ],
            options={
                "verbose_name": "クラス",
                "verbose_name_plural": "クラス",
                "db_table": "class",
            },
        ),
        migrations.CreateModel(
            name="StudentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "生徒情報",
                "verbose_name_plural": "生徒情報",
                "db_table": "student_info",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=10)),
                ("subject_type", models.CharField(max_length=50)),
                ("credits", models.PositiveIntegerField()),
                ("teachers_str", models.CharField(max_length=300)),
                ("textbooks", models.CharField(max_length=1000)),
                ("url", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "教科",
                "verbose_name_plural": "教科",
                "db_table": "subject",
            },
        ),
        migrations.CreateModel(
            name="SubjectGroupe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "教科グループ",
                "verbose_name_plural": "教科グループ",
                "db_table": "subject_groupe",
            },
        ),
        migrations.CreateModel(
            name="SyllabusDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("admission_year", models.IntegerField(verbose_name="入学年度")),
                ("code", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="TeacherInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department_type", models.CharField(default="", max_length=20)),
                ("owner", models.BooleanField(default=False)),
                ("subdomain", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "教師情報",
                "verbose_name_plural": "教師情報",
                "db_table": "teacher_info",
            },
        ),
        migrations.CreateModel(
            name="UserSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "ユーザー設定",
                "verbose_name_plural": "ユーザー設定",
                "db_table": "user_setting",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "生徒"),
                            ("teacher", "教師"),
                            ("staff", "管理者"),
                            ("system", "System"),
                            ("student_affairs", "学生課"),
                            ("unregistered", "未登録"),
                        ],
                        db_index=True,
                        default="unregistered",
                        max_length=20,
                        verbose_name="役割",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=30)),
                ("username", models.CharField(blank=True, max_length=30)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "user",
            },
            managers=[
                ("objects", content.models.user.UserManager()),
            ],
        ),
    ]
