# Generated by Django 4.2.24 on 2025-10-01 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "user"},
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="user",
            name="password_changed",
        ),
        migrations.RemoveField(
            model_name="user",
            name="password_changed_date",
        ),
    ]
