# Generated by Django 6.0.4 on 2026-04-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_alter_studentinfo_school_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="code",
            field=models.CharField(max_length=25),
        ),
    ]
