# Generated by Django 5.2.7 on 2025-10-14 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_alter_user_options_user_is_staff"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "user"},
        ),
    ]
