# Generated by Django 5.2.7 on 2025-11-04 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_alter_user_options"),
        ("core", "0009_remove_file_core_file_mine_ty_ddc73e_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamGroupe",
            fields=[
                (
                    "unique_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
            options={
                "verbose_name": "試験グループ",
                "verbose_name_plural": "試験グループ",
                "db_table": "exam_groupe",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "unique_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
            options={
                "verbose_name": "教科",
                "verbose_name_plural": "教科",
                "db_table": "subject",
            },
        ),
        migrations.CreateModel(
            name="SubjectGroupe",
            fields=[
                (
                    "unique_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
            options={
                "verbose_name": "教科グループ",
                "verbose_name_plural": "教科グループ",
                "db_table": "subject_groupe",
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "unique_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "file",
                    models.ForeignKey(
                        db_column="file_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.textfilestorage",
                        verbose_name="ファイル",
                    ),
                ),
                (
                    "exam_groupe",
                    models.ForeignKey(
                        db_column="exam_groupe_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="content.examgroupe",
                        verbose_name="試験グループ",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        db_column="subject_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="content.subject",
                        verbose_name="教科",
                    ),
                ),
            ],
            options={
                "verbose_name": "試験",
                "verbose_name_plural": "試験",
                "db_table": "exam",
            },
        ),
        migrations.AddField(
            model_name="subject",
            name="subject_groupe",
            field=models.ForeignKey(
                db_column="subject_groupe_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="content.subjectgroupe",
                verbose_name="教科グループ",
            ),
        ),
        migrations.AddField(
            model_name="examgroupe",
            name="subject_groupe",
            field=models.ForeignKey(
                db_column="subject_groupe_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="content.subjectgroupe",
                verbose_name="教科グループ",
            ),
        ),
    ]
