# Generated by Django 6.0.4 on 2026-04-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_alter_subject_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectgroupe",
            name="name",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subjectgroupe",
            name="teachers",
            field=models.ManyToManyField(
                related_name="subject_groupes",
                to="content.teacherinfo",
                verbose_name="担当講師陣",
            ),
        ),
    ]
