# Generated by Django 5.2.7 on 2025-11-04 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_examgroupe_subject_subjectgroupe_exam_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "unique_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200, verbose_name="学校名")),
                ("code", models.CharField(max_length=50, verbose_name="学校コード")),
            ],
            options={
                "verbose_name": "学校",
                "verbose_name_plural": "学校",
                "db_table": "school",
            },
        ),
        migrations.AlterField(
            model_name="exam",
            name="exam_groupe",
            field=models.ForeignKey(
                db_column="exam_groupe_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exams",
                to="content.examgroupe",
                verbose_name="試験グループ",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="subject",
            field=models.ForeignKey(
                db_column="subject_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exams",
                to="content.subject",
                verbose_name="教科",
            ),
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "unique_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("admission_year", models.IntegerField(verbose_name="入学年度")),
                (
                    "school",
                    models.ForeignKey(
                        db_column="school_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="content.school",
                        verbose_name="学校",
                    ),
                ),
            ],
            options={
                "verbose_name": "学部",
                "verbose_name_plural": "学部",
                "db_table": "department",
            },
        ),
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                (
                    "unique_id",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="一意ID",
                    ),
                ),
                ("grade", models.IntegerField(verbose_name="学年")),
                (
                    "department",
                    models.ForeignKey(
                        db_column="department_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="content.department",
                        verbose_name="学部",
                    ),
                ),
            ],
            options={
                "verbose_name": "クラス",
                "verbose_name_plural": "クラス",
                "db_table": "class",
            },
        ),
        migrations.AddField(
            model_name="examgroupe",
            name="school_class",
            field=models.ForeignKey(
                db_column="school_class_id",
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="content.schoolclass",
                verbose_name="教科グループ",
            ),
            preserve_default=False,
        ),
    ]
