# Generated by Django 6.0.4 on 2026-04-30 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_subjectgroupe_name_subjectgroupe_teachers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="subject_groupe",
            field=models.ForeignKey(
                db_column="subject_groupe_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subjects",
                to="content.subjectgroupe",
                verbose_name="教科グループ",
            ),
        ),
    ]
