# Generated by Django 5.2.7 on 2025-11-04 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_school_alter_exam_exam_groupe_alter_exam_subject_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="school",
        ),
        migrations.RemoveField(
            model_name="schoolclass",
            name="department",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="exam_groupe",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="file",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="examgroupe",
            name="school_class",
        ),
        migrations.RemoveField(
            model_name="examgroupe",
            name="subject_groupe",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="subject_groupe",
        ),
        migrations.DeleteModel(
            name="School",
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="Exam",
        ),
        migrations.DeleteModel(
            name="SchoolClass",
        ),
        migrations.DeleteModel(
            name="ExamGroupe",
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
        migrations.DeleteModel(
            name="SubjectGroupe",
        ),
    ]
