# Generated by Django 5.2.7 on 2025-11-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_school_alter_exam_exam_groupe_alter_exam_subject_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="unique_id",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="unique_id",
        ),
        migrations.RemoveField(
            model_name="examgroupe",
            name="unique_id",
        ),
        migrations.RemoveField(
            model_name="school",
            name="unique_id",
        ),
        migrations.RemoveField(
            model_name="schoolclass",
            name="unique_id",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="unique_id",
        ),
        migrations.RemoveField(
            model_name="subjectgroupe",
            name="unique_id",
        ),
        migrations.AddField(
            model_name="department",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="examgroupe",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="subjectgroupe",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
