# Generated by Django 5.2.7 on 2025-11-04 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_remove_department_school_and_more"),
        ("core", "0009_remove_file_core_file_mine_ty_ddc73e_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="学校名")),
                ("code", models.CharField(max_length=50, verbose_name="学校コード")),
            ],
            options={
                "verbose_name": "学校",
                "verbose_name_plural": "学校",
                "db_table": "school",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "教科",
                "verbose_name_plural": "教科",
                "db_table": "subject",
            },
        ),
        migrations.CreateModel(
            name="SubjectGroupe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "教科グループ",
                "verbose_name_plural": "教科グループ",
                "db_table": "subject_groupe",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admission_year", models.IntegerField(verbose_name="入学年度")),
                (
                    "school",
                    models.ForeignKey(
                        db_column="school_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="content.school",
                        verbose_name="学校",
                    ),
                ),
            ],
            options={
                "verbose_name": "学部",
                "verbose_name_plural": "学部",
                "db_table": "department",
            },
        ),
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.IntegerField(verbose_name="学年")),
                (
                    "department",
                    models.ForeignKey(
                        db_column="department_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="content.department",
                        verbose_name="学部",
                    ),
                ),
            ],
            options={
                "verbose_name": "クラス",
                "verbose_name_plural": "クラス",
                "db_table": "class",
            },
        ),
        migrations.CreateModel(
            name="ExamGroupe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        db_column="school_class_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="content.schoolclass",
                        verbose_name="教科グループ",
                    ),
                ),
                (
                    "subject_groupe",
                    models.ForeignKey(
                        db_column="subject_groupe_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="content.subjectgroupe",
                        verbose_name="教科グループ",
                    ),
                ),
            ],
            options={
                "verbose_name": "試験グループ",
                "verbose_name_plural": "試験グループ",
                "db_table": "exam_groupe",
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        db_column="file_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.textfilestorage",
                        verbose_name="ファイル",
                    ),
                ),
                (
                    "exam_groupe",
                    models.ForeignKey(
                        db_column="exam_groupe_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exams",
                        to="content.examgroupe",
                        verbose_name="試験グループ",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        db_column="subject_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exams",
                        to="content.subject",
                        verbose_name="教科",
                    ),
                ),
            ],
            options={
                "verbose_name": "試験",
                "verbose_name_plural": "試験",
                "db_table": "exam",
            },
        ),
        migrations.AddField(
            model_name="subject",
            name="subject_groupe",
            field=models.ForeignKey(
                db_column="subject_groupe_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="content.subjectgroupe",
                verbose_name="教科グループ",
            ),
        ),
    ]
