# Generated by Django 5.2.7 on 2025-11-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "content",
            "0008_school_subject_subjectgroupe_department_schoolclass_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="department",
            name="url",
            field=models.CharField(default="a", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="school",
            name="url",
            field=models.CharField(default="aaa", max_length=100),
            preserve_default=False,
        ),
    ]
