# Generated by Django 5.2.7 on 2025-11-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_department_name_department_url_school_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="code",
            field=models.CharField(default="1121212", max_length=10),
            preserve_default=False,
        ),
    ]
