# Generated by Django 5.2.7 on 2025-11-04 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0010_department_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="school_class",
            field=models.ForeignKey(
                db_column="class_id",
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subjects",
                to="content.schoolclass",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="subject",
            name="subject_groupe",
            field=models.ForeignKey(
                db_column="subject_groupe_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subjects",
                to="content.subjectgroupe",
                verbose_name="教科グループ",
            ),
        ),
    ]
