# Generated by Django 5.2.7 on 2025-11-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0011_subject_school_class_alter_subject_subject_groupe"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolclass",
            name="grade_str",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="subject",
            name="code",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject",
            name="credits",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject",
            name="name",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject",
            name="subject_type",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject",
            name="teachers",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject",
            name="textbooks",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject",
            name="url",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
