# Generated by Django 5.2.7 on 2025-11-04 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0012_schoolclass_grade_str_subject_code_subject_credits_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schoolclass",
            name="grade_str",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="code",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="credits",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="name",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="school_class",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="subject_type",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="teachers",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="textbooks",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="url",
        ),
    ]
