# Generated by Django 5.2.7 on 2025-11-04 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0013_remove_schoolclass_grade_str_remove_subject_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolclass",
            name="grade_str",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="subject",
            name="code",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject",
            name="credits",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject",
            name="name",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject",
            name="school_class",
            field=models.ForeignKey(
                db_column="class_id",
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subjects",
                to="content.schoolclass",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject",
            name="subject_type",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject",
            name="teachers",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject",
            name="textbooks",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject",
            name="url",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
