# Generated by Django 5.2.7 on 2025-11-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0015_add_fix_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="url",
            field=models.CharField(max_length=200),
        ),
    ]
