# Generated by Django 5.2.7 on 2025-11-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0016_alter_subject_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="teachers",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="subject",
            name="textbooks",
            field=models.CharField(max_length=500),
        ),
    ]
