# Generated by Django 5.2.7 on 2025-11-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0017_alter_subject_teachers_alter_subject_textbooks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="textbooks",
            field=models.CharField(max_length=1000),
        ),
    ]
