# Generated by Django 5.2.7 on 2025-11-04 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0018_alter_subject_textbooks"),
        ("core", "0009_remove_file_core_file_mine_ty_ddc73e_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="exam_groupe",
            field=models.ForeignKey(
                db_column="exam_groupe_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="content.examgroupe",
                verbose_name="試験グループ",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="file",
            field=models.ForeignKey(
                db_column="file_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.textfilestorage",
                verbose_name="ファイル",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="subject",
            field=models.ForeignKey(
                db_column="subject_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="content.subject",
                verbose_name="教科",
            ),
        ),
        migrations.AlterField(
            model_name="examgroupe",
            name="school_class",
            field=models.ForeignKey(
                db_column="school_class_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="content.schoolclass",
                verbose_name="教科グループ",
            ),
        ),
        migrations.AlterField(
            model_name="examgroupe",
            name="subject_groupe",
            field=models.ForeignKey(
                db_column="subject_groupe_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="content.subjectgroupe",
                verbose_name="教科グループ",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="school_class",
            field=models.ForeignKey(
                db_column="class_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="content.schoolclass",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="subject_groupe",
            field=models.ForeignKey(
                db_column="subject_groupe_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="content.subjectgroupe",
                verbose_name="教科グループ",
            ),
        ),
    ]
