# Generated by Django 5.2.7 on 2025-11-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0019_alter_exam_exam_groupe_alter_exam_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="subject_type",
            field=models.CharField(max_length=50),
        ),
    ]
