# Generated by Django 5.2.7 on 2025-11-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0020_alter_subject_subject_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolclass",
            name="year",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="schoolclass",
            name="grade",
            field=models.PositiveIntegerField(verbose_name="補正学年"),
        ),
        migrations.AlterField(
            model_name="schoolclass",
            name="grade_str",
            field=models.CharField(default="学年", max_length=10),
        ),
    ]
