# Generated by Django 5.2.7 on 2025-11-06 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0021_schoolclass_year_alter_schoolclass_grade_and_more"),
        ("core", "0009_remove_file_core_file_mine_ty_ddc73e_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="content",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exam",
            name="goal",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exam",
            name="quarter",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exam",
            name="url",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exam",
            name="week",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="exam",
            name="exam_groupe",
            field=models.ForeignKey(
                db_column="exam_groupe_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="content.examgroupe",
                verbose_name="試験グループ",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="file",
            field=models.ForeignKey(
                db_column="file_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.textfilestorage",
                verbose_name="ファイル",
            ),
        ),
    ]
