# Generated by Django 5.2.8 on 2025-11-06 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0022_exam_content_exam_goal_exam_quarter_exam_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subject",
            old_name="teachers",
            new_name="teachers_str",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "生徒"),
                    ("teacher", "教師"),
                    ("school_staff", "その他"),
                ],
                default="student",
                max_length=20,
                verbose_name="役割",
            ),
        ),
        migrations.CreateModel(
            name="StudentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        db_column="school_class_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="content.schoolclass",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "生徒情報",
                "verbose_name_plural": "生徒情報",
                "db_table": "student_info",
            },
        ),
        migrations.CreateModel(
            name="TeacherInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        related_name="teachers",
                        to="content.subject",
                        verbose_name="担当教科",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "教師情報",
                "verbose_name_plural": "教師情報",
                "db_table": "teacher_info",
            },
        ),
        migrations.CreateModel(
            name="UserSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_setting",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ユーザー設定",
                "verbose_name_plural": "ユーザー設定",
                "db_table": "user_setting",
            },
        ),
    ]
