# Generated by Django 5.2.8 on 2025-11-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0023_rename_teachers_subject_teachers_str_user_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "生徒"),
                    ("teacher", "教師"),
                    ("staff", "管理者"),
                    ("system", "System"),
                    ("other", "その他"),
                ],
                db_index=True,
                default="other",
                max_length=20,
                verbose_name="役割",
            ),
        ),
    ]
