# Generated by Django 5.2.8 on 2025-11-12 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0024_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentinfo",
            name="student_id",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacherinfo",
            name="owner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="studentinfo",
            name="school_class",
            field=models.ForeignKey(
                blank=True,
                db_column="school_class_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="content.schoolclass",
            ),
        ),
        migrations.AlterField(
            model_name="teacherinfo",
            name="subjects",
            field=models.ManyToManyField(
                blank=True,
                related_name="teachers",
                to="content.subject",
                verbose_name="担当教科",
            ),
        ),
    ]
