# Generated by Django 5.2.8 on 2025-11-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0025_studentinfo_student_id_teacherinfo_owner_user_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
