# Generated by Django 5.2.8 on 2025-11-12 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0026_alter_user_name_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentinfo",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="content.department",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacherinfo",
            name="school",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teachers",
                to="content.school",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
