# Generated by Django 5.2.8 on 2025-11-12 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0027_studentinfo_department_teacherinfo_school_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentinfo",
            name="school_class_history",
            field=models.ManyToManyField(
                related_name="students", to="content.schoolclass"
            ),
        ),
        migrations.AlterField(
            model_name="studentinfo",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="content.department",
            ),
        ),
        migrations.AlterField(
            model_name="studentinfo",
            name="school_class",
            field=models.ForeignKey(
                blank=True,
                db_column="school_class_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="now_students",
                to="content.schoolclass",
            ),
        ),
        migrations.AlterField(
            model_name="teacherinfo",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teachers",
                to="content.school",
            ),
        ),
    ]
