# Generated by Django 5.2.8 on 2025-11-12 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0028_studentinfo_school_class_history_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentinfo",
            old_name="school_class_history",
            new_name="class_history",
        ),
    ]
