# Generated by Django 5.2.8 on 2025-11-12 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0029_rename_school_class_history_studentinfo_class_history"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentinfo",
            name="class_history",
        ),
        migrations.RemoveField(
            model_name="studentinfo",
            name="school_class",
        ),
    ]
