# Generated by Django 5.2.8 on 2025-11-16 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0030_remove_studentinfo_class_history_and_more"),
        ("core", "0009_remove_file_core_file_mine_ty_ddc73e_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="admission_year",
        ),
        migrations.RemoveField(
            model_name="department",
            name="code",
        ),
        migrations.RemoveField(
            model_name="department",
            name="url",
        ),
        migrations.RemoveField(
            model_name="examgroupe",
            name="school_class",
        ),
        migrations.RemoveField(
            model_name="schoolclass",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="schoolclass",
            name="grade_str",
        ),
        migrations.RemoveField(
            model_name="schoolclass",
            name="year",
        ),
        migrations.RemoveField(
            model_name="studentinfo",
            name="department",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="school_class",
        ),
        migrations.RemoveField(
            model_name="teacherinfo",
            name="school",
        ),
    ]
