# Generated by Django 5.2.8 on 2025-11-16 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0030_remove_studentinfo_class_history_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="admission_year",
        ),
        migrations.RemoveField(
            model_name="department",
            name="code",
        ),
        migrations.RemoveField(
            model_name="department",
            name="url",
        ),
        migrations.RemoveField(
            model_name="examgroupe",
            name="school_class",
        ),
        migrations.RemoveField(
            model_name="schoolclass",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="schoolclass",
            name="grade_str",
        ),
        migrations.RemoveField(
            model_name="schoolclass",
            name="year",
        ),
        migrations.RemoveField(
            model_name="studentinfo",
            name="department",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="school_class",
        ),
        migrations.RemoveField(
            model_name="teacherinfo",
            name="school",
        ),
        migrations.AddField(
            model_name="examgroupe",
            name="subject",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.subject",
                verbose_name="教科グループ",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="admission_year",
            field=models.IntegerField(default=0, verbose_name="入学年度"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentinfo",
            name="school_class",
            field=models.ForeignKey(
                blank=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.schoolclass",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacherinfo",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teachers",
                to="content.department",
            ),
        ),
        migrations.AddField(
            model_name="teacherinfo",
            name="subdomain",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="GradeClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade_str", models.CharField(default="学年", max_length=10)),
                ("grade", models.PositiveIntegerField(verbose_name="補正学年")),
                ("year", models.PositiveIntegerField()),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="content.schoolclass",
                        verbose_name="クラス",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="subject",
            name="grade_class",
            field=models.ForeignKey(
                db_column="class_id",
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="content.gradeclass",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="SyllabusDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("admission_year", models.IntegerField(verbose_name="入学年度")),
                ("code", models.CharField(max_length=10)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syllabus_departments",
                        to="content.department",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        db_column="school_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syllabus_departments",
                        to="content.school",
                        verbose_name="学校",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="syllabus_department",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="content.syllabusdepartment",
                verbose_name="シラバス学部",
            ),
            preserve_default=False,
        ),
    ]
