# Generated by Django 5.2.8 on 2025-11-16 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0031_remove_department_admission_year_and_more"),
        ("core", "0009_remove_file_core_file_mine_ty_ddc73e_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="examgroupe",
            name="subject",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.subject",
                verbose_name="教科グループ",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="admission_year",
            field=models.IntegerField(default=1, verbose_name="入学年度"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentinfo",
            name="school_class",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.schoolclass",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacherinfo",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teachers",
                to="content.department",
            ),
        ),
        migrations.AddField(
            model_name="teacherinfo",
            name="subdomain",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="exam",
            name="exam_groupe",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="content.examgroupe",
                verbose_name="試験グループ",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="file",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.textfilestorage",
                verbose_name="ファイル",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="content.subject",
                verbose_name="教科",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "生徒"),
                    ("teacher", "教師"),
                    ("staff", "管理者"),
                    ("system", "System"),
                    ("student_affairs", "学生課"),
                    ("unregistered", "未登録"),
                ],
                db_index=True,
                default="unregistered",
                max_length=20,
                verbose_name="役割",
            ),
        ),
        migrations.CreateModel(
            name="GradeClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade_str", models.CharField(default="学年", max_length=10)),
                ("grade", models.PositiveIntegerField(verbose_name="補正学年")),
                ("year", models.PositiveIntegerField()),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="content.schoolclass",
                        verbose_name="クラス",
                    ),
                ),
            ],
        ),
    ]
