# Generated by Django 5.2.8 on 2025-11-16 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0032_examgroupe_subject_schoolclass_admission_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="grade_class",
            field=models.ForeignKey(
                db_column="class_id",
                # default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="content.gradeclass",
                null=True,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="SyllabusDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("admission_year", models.IntegerField(verbose_name="入学年度")),
                ("code", models.CharField(max_length=10)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syllabus_departments",
                        to="content.department",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        db_column="school_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syllabus_departments",
                        to="content.school",
                        verbose_name="学校",
                    ),
                ),
            ],
        ),
    ]
