# Generated by Django 5.2.8 on 2025-11-16 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0033_subject_grade_class_syllabusdepartment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolclass",
            name="syllabus_department",
            field=models.ForeignKey(
                # default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="content.syllabusdepartment",
                verbose_name="シラバス学部",
                null=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="subject",
            name="grade_class",
            field=models.ForeignKey(
                db_column="class_id",
                # default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="content.gradeclass",
                null=True,
            ),
            preserve_default=False,
        ),
    ]
