# Generated by Django 5.2.8 on 2025-11-16 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0034_schoolclass_syllabus_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolclass",
            name="syllabus_department",
            field=models.ForeignKey(
                # default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="content.syllabusdepartment",
                verbose_name="シラバス学部",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="studentinfo",
            name="school_class",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.schoolclass",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="grade_class",
            field=models.ForeignKey(
                db_column="class_id",
                # default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="content.gradeclass",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="syllabusdepartment",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="syllabus_departments",
                to="content.department",
            ),
        ),
        migrations.AlterField(
            model_name="teacherinfo",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teachers",
                to="content.department",
            ),
        ),
        migrations.AlterField(
            model_name="teacherinfo",
            name="subjects",
            field=models.ManyToManyField(
                null=True,
                related_name="teachers",
                to="content.subject",
                verbose_name="担当教科",
            ),
        ),
    ]
