# Generated by Django 5.2.8 on 2025-11-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0035_alter_schoolclass_syllabus_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherinfo",
            name="department_type",
            field=models.CharField(default="", max_length=20),
        ),
    ]
