# Generated by Django 5.2.8 on 2025-11-17 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0036_teacherinfo_department_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentinfo",
            name="school_class",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="content.schoolclass",
            ),
            preserve_default=False,
        ),
    ]
