# Generated by Django 6.0.4 on 2026-04-13 06:18

import core.models.file
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapyItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("scrape_id", models.CharField(max_length=100, null=True)),
                ("item_name", models.TextField(null=True)),
                ("spider_name", models.TextField(null=True)),
                ("data", models.TextField()),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=core.models.file.upload_to_uuid,
                        verbose_name="ファイル",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="元のファイル名"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="ファイルサイズ"),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="コンテンツタイプ"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="説明"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="アップロード日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="アップロードユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "ファイル",
                "verbose_name_plural": "ファイル",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["-uploaded_at"], name="core_file_uploade_bd9cc5_idx"
                    ),
                    models.Index(
                        fields=["uploaded_by"], name="core_file_uploade_4cec07_idx"
                    ),
                    models.Index(
                        fields=["mime_type"], name="core_file_mime_ty_523ed6_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TextFileStorage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="キーに使用できるのは英数字、(-), (_), (:), (/), (.)のみ",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "body",
                    models.TextField(blank=True, help_text="ファイルの内容", null=True),
                ),
                ("mime_type", models.CharField(blank=True, max_length=100, null=True)),
                ("file_size", models.IntegerField(default=0)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "テキストファイル",
                "verbose_name_plural": "テキストファイル一覧",
                "db_table": "text_file_storage",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["key"], name="text_file_s_key_9b802d_idx")
                ],
            },
        ),
    ]
