# Generated by Django 5.2.7 on 2025-10-15 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TextFileStorage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="ファイル名やパス（英数字、ハイフン、アンダースコア、ドット）",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "body",
                    models.TextField(blank=True, help_text="ファイルの内容", null=True),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True,
                        help_text="例: text/plain, application/json",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        default=0, help_text="ファイルサイズ（バイト単位）"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, help_text="論理削除フラグ"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "テキストファイル",
                "verbose_name_plural": "テキストファイル一覧",
                "db_table": "text_file_storage",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["key"], name="text_file_s_key_9b802d_idx")
                ],
            },
        ),
    ]
