# Generated by Django 5.2.7 on 2025-10-21 05:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_scrapyitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapyitem",
            name="scrape_id",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="scrapyitem",
            name="unique_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
