# Generated by Django 5.2.7 on 2025-10-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_scrapyitem_scrape_id_alter_scrapyitem_unique_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapyitem",
            name="item_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="scrapyitem",
            name="spider_name",
            field=models.TextField(null=True),
        ),
    ]
