# Generated by Django 5.2.7 on 2025-10-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_scrapyitem_item_name_scrapyitem_spider_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textfilestorage",
            name="file_size",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="textfilestorage",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="textfilestorage",
            name="key",
            field=models.CharField(
                db_index=True,
                help_text="キーに使用できるのは英数字、(-), (_), (:), (/), (.)のみ",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="textfilestorage",
            name="mine_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
