# Generated by Django 5.2.7 on 2025-10-22 22:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_textfilestorage_file_size_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="file",
            name="core_file_mine_ty_ddc73e_idx",
        ),
        migrations.RenameField(
            model_name="file",
            old_name="mine_type",
            new_name="mime_type",
        ),
        migrations.RenameField(
            model_name="textfilestorage",
            old_name="mine_type",
            new_name="mime_type",
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["mime_type"], name="core_file_mime_ty_523ed6_idx"
            ),
        ),
    ]
